package com.uvezem.model

data class DeliveriesItem(val status: Int = 0,
                          val coordinateLoadLat: Double?,
                          val organization: String?,
                          val addressWarehouse: String?,
//                          val entityName: Null = null,
//                          val truckName: Null = null,
//                          val driverName: Null = null,
                          val refrigerator: Boolean = false,
                          val deliveryPoints: List<DeliveryPoint>?,
                          val trailName: String?,
                          val priceDelivery: Int = 0,
                          val coordinateLoadLon: Double = 0.0,
                          val date: String = "",
                          val weight: Int = 0,
                          val offerId: String?,
                          val logistPhone: String?,
                          val number: Int = 0,
                          val volume: Int = 0,
                          val dateShipment: String = "",
                          val numberDelivery: Int = 0,
                          val id: Int = 0,
                          val cargoType: String = "")